### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by icansleep22hours** [stbenke/SpectralUnmixR#1]
![image](https://user-images.githubusercontent.com/86293485/191694003-a2de1ce7-c40a-46de-bae7-30db5603eab3.png)
I am not sure what the problem is. I have installed the BiocManager and flowCore.

**Comment by stbenke** [comment]
That is weird, because all_of is exported by tidyr and it did not gave troubles on all PCs we installed it. Anyway I changed the reference now to the more appropriate tidyselect. On my side, installation is still working. Can you try again and see if it works for you now as well?

**Comment by icansleep22hours** [comment]
Thanks a lot. I can install the package now.
